name: "Release"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: "🛎 Checkout"
        uses: actions/checkout@v3
      - name: "🔧 Setup"
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - name: "📦 Install"
        run: yarn global add semantic-release @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/npm @semantic-release/github @semantic-release/git @semantic-release/changelog
      - name: "🔖 Release"
        env:
          # appears on the release commits
          GIT_AUTHOR_NAME: agoralabs-bot
          GIT_AUTHOR_EMAIL: tech@agoralabs.sh
          GIT_COMMITTER_NAME: agoralabs-bot
          GIT_COMMITTER_EMAIL: tech@agoralabs.sh
          # used to push the release commit and create the tags
          GITHUB_TOKEN: ${{ secrets.WRITE_REPOS_TOKEN }}
        run: semantic-release
